### ISSUE TITLE
Set up environment

### ISSUE THREAD

**Issue by SMTDOO** [EfficientElevator28/Simulation#1]
Get the foundation set up for seamless (cough cough) coding

**Comment by SMTDOO** [comment]
Not it

**Comment by Dando18** [comment]
I can do this. I'll set up a python environment with the proper src and doc folders along with some goals for the end product.

**Comment by obarbour** [comment]
By the way, we are using spaces instead of tabs for this project.

**Comment by obarbour** [comment]
Failed to actually link any commits but this is done.
