### ISSUE TITLE
Implement elevator physics

### ISSUE THREAD

**Issue by SMTDOO** [EfficientElevator28/Simulation#5]
Make elevator realistic

**Comment by obarbour** [comment]
Programmatically, we could precompute the floor distance travel times (ex. calculate the 1 floor, 2 floor, etc. travel times) based on the physics constants we have entered.

**Comment by obarbour** [comment]
Waiting on step function to know exactly how to proceed.

**Comment by obarbour** [comment]
Possible limitation (but may be fine): physics may break down if the floor that the elevator is currently going to is removed from the queue.

**Comment by obarbour** [comment]
> Possible limitation (but may be fine): physics may break down if the floor that the elevator is currently going to is removed from the queue.

Decided that we will never alter the first floor in the elevator queue, only the second (there will only be two elements at any time).

**Comment by obarbour** [comment]
The only thing to do, besides fix bugs if they arise, is to create a function that checks if the elevator can stop by a particular floor. This function would be used by a baseline comparison if we were to do one. Closing under the assumption that this won't be developed further.
